### ISSUE TITLE
Unexpected data format errors

### ISSUE THREAD

**Issue by elisabeth-chen** [CancerRxGene/gdsctools#146] opened 2016-06-25 20:55 UTC
Using the example files attached below, several errors come up when calling:

an = gdsctools.ANOVA( "ic50_matrix.csv", "genomic_features.csv" )

Fixed by: 
* changing MSI_FACTOR to integers instead of strings
* changing header of "MEDIA_FACTOR" to "media_factor"

But still seems to give wrong format for Media factor and Tissue factor.

[test_files.zip](https://github.com/CancerRxGene/gdsctools/files/333279/test_files.zip)

**Comment by cokelaer** [comment] 2016-06-26 20:24
MSI factor must be either 0 or 1. In the genomic_features_matrix file, you have indeed strings such as 
MSI-H or MSS/MSI-L so they should be replaced with proper integers

As for the media factor, the header should  MEDIA_FACTOR . The error you get is a bug, which is now fixed in the master branch. 

However, note that once fixed, there will be a warning and MEDIA factor will not be included. 
The reason being that the ANOVA analysis does not include the MEDIA factor withouth a PAN-cancer data and without MSI. In you case you have only once tissue. See ANOVA equations here : http://gdsctools.readthedocs.io/en/master/anova_parttwo.html#regression-analysis

**Closed** 2016-06-27 06:24 UTC
